//
// Created by Amichai Malle on 09/01/2023.
//

#ifndef SYSTEM_PROGRAMING_CPP_ORTHOGONALTRIANGLE_H
#define SYSTEM_PROGRAMING_CPP_ORTHOGONALTRIANGLE_H


class OrthogonalTriangle {

};


#endif //SYSTEM_PROGRAMING_CPP_ORTHOGONALTRIANGLE_H
